### ISSUE TITLE
mc-http-server does not start

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1483]
We are facing an issue in all our custom apps, we are pulling this image

FROM eu.gcr.io/ct-images/mc-http-server:v11.2.0

And now the log show us, that a module is missing.
Can you help us with that?

Let me know if need more logs or more information for us.

<img width="1050" alt="Captura de Pantalla 2020-05-08 a la(s) 12 25 48" src="https://user-images.githubusercontent.com/29213153/81430224-17f96e80-912d-11ea-83f0-b84d73ec1334.png">

**Comment by patti29** [comment]
Complete error 

Error: Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'
Require stack:
- /app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js
- /app/node_modules/@commercetools-frontend/mc-html-template/build/index.js
- /app/bin/start-mc.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15) 
at Function.Module._load (internal/modules/cjs/loader.js:838:27)
at Module.require (internal/modules/cjs/loader.js:1022:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js:3:30)
at Module._compile (internal/modules/cjs/loader.js:1118:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
at Module.load (internal/modules/cjs/loader.js:982:32)
at Function.Module._load (internal/modules/cjs/loader.js:875:14)
at Module.require (internal/modules/cjs/loader.js:1022:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js',
'/app/node_modules/@commercetools-frontend/mc-html-template/build/index.js',
'/app/bin/start-mc.js'
]
}
internal/modules/cjs/loader.js:965
throw err;
^

**Comment by emmenko** [comment]
Hi, thanks for reaching out to us.

On top of my head, I don't know what the issue might be.

Have you tried using a more recent version of the image? If you just started developing Custom Applications you should use version >=16 (currently latest is `v16.8.0`).

If not, was the app already running for some time? Did you get the error only now?

**Comment by tdeekens** [comment]
This is really odd. We use the same images ourselves and have not seen this issue. Have you tried another version maybe?

**Comment by patti29** [comment]
We have not seen the issue using 
`mc-http-server:v11.2.0` from last 1 year , although we are trying to validate with new version.

Will keep you informed

**Comment by patti29** [comment]
We are facing same issue while using the latest version

**Comment by emmenko** [comment]
Hmm, what node version are you using?

**Comment by tdeekens** [comment]
Can you share more precisely what you do so we can reproduce the issue on our side? That would help. As we‘re also using the latest image but without issues. As a result we would like to know what steps you are taking. Thanks

**Comment by roger1345** [comment]
We notice that we were using :latest for all our custom apps instances, and the "latest" tag was asign to 16.8.0 and cause the error, in our instances. We are making the change to use another version. We let you know if we solve the issue in a few minutes. Thank you all for the quickly response.

![image](https://user-images.githubusercontent.com/20628186/81445638-408e6200-9147-11ea-8f27-cd4fdb0d7ca6.png)

**Comment by emmenko** [comment]
Ah good to know. We haven't tried the latest release yet in our internal apps...so maybe something is broken there.

Version `v16.7.0` should work though, as we are running it on production.

**Comment by emmenko** [comment]
I can confirm that I can reproduce the error with the `v16.8.0` image

```
docker run --rm -it eu.gcr.io/ct-images/mc-http-server 
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'
Require stack:
- /app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js
- /app/node_modules/@commercetools-frontend/mc-html-template/build/index.js
- /app/bin/start-mc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js',
    '/app/node_modules/@commercetools-frontend/mc-html-template/build/index.js',
    '/app/bin/start-mc.js'
  ]
}
```

We'll look into it. Thanks again for reporting the issue and apologies for the inconvenience.
