### ISSUE TITLE
Typescript starter tests are failing

### ISSUE THREAD

**Issue by jluterek** [commercetools/merchant-center-application-kit#3498]
I did find a closed issue with the same problem - https://github.com/commercetools/merchant-center-application-kit/issues/3443

**Describe the issue**

A fresh copy of the typescript starter fails when running yarn test.

**To Reproduce**

Execute the following steps.

> npx @commercetools-frontend/create-mc-app@latest   custom-app-starter   --template starter-typescript
Provide the Custom Application entryPointUriPath (default "starter-typescript-a1da0a"):
Provide the initial project key for local development: dev-1

> cd custom-app-starter

> yarn test

**Expected behavior**

Pass all tests.

![image](https://github.com/commercetools/merchant-center-application-kit/assets/17462045/aacdd5a4-5663-46c6-8eca-6b5bb0cca6e0)
![image](https://github.com/commercetools/merchant-center-application-kit/assets/17462045/5d1aa03c-a483-41ef-a95f-b9312d149204)

**Additional context**

This fails on both local development and when run through github actions.

Test Suites: 2 failed, 1 passed, 3 total
Tests:       9 failed, 1 passed, 10 total
Snapshots:   0 total

`$ jest --config jest.test.config.js
 PASS   test  src/components/welcome/welcome.spec.tsx
 FAIL   test  src/components/channels/channels.spec.tsx
  ● should render channels and paginate to second page

    Unable to find an element with the text: channel-key-0. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    Ignored nodes: comments, script, style
    <body>
      <div>
        <div
          style=""
        >
          <div
            class="css-m39x7a-baseStyles-getStyles"
            id="notifications-global"
          />
          <div
            class="css-177j1rc-baseStyles-getStyles"
            id="notifications-page"
          />
          <div
            class="css-88slgd-baseStyles-getStyles"
            id="notifications-side"
          />
          <div
            class="css-6ent15-Inset"
          >
            <div
              class="css-hig09w-ContentNotification"
            >
              <div
                class="css-1n4f74p-NotificationTypeIcon"
              >
                <svg
                  class="css-n970in-getIconStyles"
                  height="24"
                  role="img"
                  viewBox="0 0 24 24"
                  width="24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 21a8.8 8.8 0 0 1-3.511-.709 9 9 0 0 1-2.857-1.933 9.2 9.2 0 0 1-1.923-2.868A8.8 8.8 0 0 1 3 11.979q0-1.869.709-3.502a9.1 9.1 0 0 1 1.923-2.846 9.1 9.1 0 0 1 2.857-1.922A8.8 8.8 0 0 1 12 3q1.869 0 3.512.709a9.1 9.1 0 0 1 2.857 1.922 9.1 9.1 0 0 1 1.922 2.846A8.7 8.7 0 0 1 21 11.98a8.8 8.8 0 0 1-.709 3.511 9.2 9.2 0 0 1-1.922 2.868 9 9 0 0 1-2.857 1.933A8.8 8.8 0 0 1 12 21m0-2.277q2.814 0 4.768-1.965 1.956-1.966 1.955-4.78 0-1.052-.31-2.04a6.4 6.4 0 0 0-.936-1.847l-9.365 9.365q.816.645 1.826.955 1.01.312 2.062.312m-5.477-2.857 9.343-9.386a6.5 6.5 0 0 0-1.836-.902q-.977-.3-2.03-.301-2.814 0-4.768 1.943-1.955 1.945-1.955 4.759 0 1.052.31 2.04.313.989.936 1.847"
                  />
                </svg>
              </div>
              <div
                class="css-n4x9n6-ContentNotification"
              >
                <p
                  class="css-g23bwx-bodyStyles"
                >
                  Error message not found.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>

      70 |
      71 |   // First page
    > 72 |   await screen.findByText('channel-key-0');
         |                ^
      73 |   expect(screen.queryByText('channel-key-22')).not.toBeInTheDocument();
      74 |
      75 |   // Go to second page

      at waitForWrapper (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:166:27)
      at node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:86:33
      at Object.findByText (src/components/channels/channels.spec.tsx:72:16)`
  
  **Closed Ticket had a merge related to packages. Here is the package.json**
  
  `{
  "name": "custom-app-starter",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "build": "mc-scripts build",
    "start": "mc-scripts start",
    "compile-html": "mc-scripts compile-html",
    "compile-html:local": "MC_APP_ENV=development mc-scripts compile-html --transformer @commercetools-frontend/mc-dev-authentication/transformer-local.js",
    "start:prod:local": "npm run compile-html:local && mc-scripts serve",
    "extract-intl": "formatjs extract --format=./intl-formatter.js --out-file=./src/i18n/data/core.json 'src/**/!(*.spec).(ts|tsx)'",
    "test": "jest --config jest.test.config.js",
    "test:watch": "jest --config jest.test.config.js --watch",
    "lint": "jest --config jest.eslint.config.js",
    "format": "prettier --write '**/*.{js,ts,tsx}'",
    "typecheck": "tsc --noEmit",
    "versions:appkit": "manypkg upgrade @commercetools-frontend",
    "versions:uikit": "manypkg upgrade @commercetools-uikit"
  },
  "dependencies": {
    "@apollo/client": "3.7.14",
    "@babel/core": "^7.22.17",
    "@babel/runtime-corejs3": "^7.22.15",
    "@commercetools-frontend/actions-global": "22.23.3",
    "@commercetools-frontend/application-components": "22.23.3",
    "@commercetools-frontend/application-config": "22.23.3",
    "@commercetools-frontend/application-shell": "22.23.3",
    "@commercetools-frontend/application-shell-connectors": "22.23.3",
    "@commercetools-frontend/assets": "22.23.3",
    "@commercetools-frontend/constants": "22.23.3",
    "@commercetools-frontend/eslint-config-mc-app": "22.23.3",
    "@commercetools-frontend/i18n": "22.23.3",
    "@commercetools-frontend/jest-preset-mc-app": "22.23.3",
    "@commercetools-frontend/l10n": "22.23.3",
    "@commercetools-frontend/mc-dev-authentication": "22.23.3",
    "@commercetools-frontend/mc-scripts": "22.23.3",
    "@commercetools-frontend/permissions": "22.23.3",
    "@commercetools-test-data/channel": "7.4.0",
    "@commercetools-test-data/commons": "7.4.0",
    "@commercetools-test-data/core": "7.4.0",
    "@commercetools-uikit/constraints": "^19.0.0",
    "@commercetools-uikit/data-table": "^19.0.0",
    "@commercetools-uikit/flat-button": "^19.0.0",
    "@commercetools-uikit/grid": "^19.0.0",
    "@commercetools-uikit/hooks": "^19.0.0",
    "@commercetools-uikit/icons": "^19.0.0",
    "@commercetools-uikit/link": "^19.0.0",
    "@commercetools-uikit/loading-spinner": "^19.0.0",
    "@commercetools-uikit/localized-text-field": "^19.0.0",
    "@commercetools-uikit/localized-text-input": "^19.0.0",
    "@commercetools-uikit/notifications": "^19.0.0",
    "@commercetools-uikit/pagination": "^19.0.0",
    "@commercetools-uikit/select-field": "^19.0.0",
    "@commercetools-uikit/spacings": "^19.0.0",
    "@commercetools-uikit/text": "^19.0.0",
    "@commercetools-uikit/text-field": "^19.0.0",
    "@commercetools-uikit/text-input": "^19.0.0",
    "@commercetools/sync-actions": "^5.14.0",
    "@emotion/react": "^11.11.4",
    "@formatjs/cli": "6.2.7",
    "@jest/types": "29.6.3",
    "@manypkg/cli": "0.21.3",
    "@testing-library/dom": "^9.3.1",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "12.1.5",
    "@testing-library/react-hooks": "8.0.1",
    "@types/jest": "^29.5.4",
    "@types/react": "^17.0.56",
    "@types/react-dom": "^17.0.19",
    "@types/react-router": "^5.1.20",
    "@types/react-router-dom": "^5.3.3",
    "@types/testing-library__jest-dom": "^5.14.9",
    "eslint": "8.57.0",
    "eslint-formatter-pretty": "4.1.0",
    "eslint-plugin-graphql": "^4.0.0",
    "formik": "2.2.9",
    "graphql": "^16.8.0",
    "graphql-tag": "^2.12.6",
    "jest": "29.7.0",
    "jest-runner-eslint": "2.2.0",
    "jest-watch-typeahead": "2.2.2",
    "moment": "^2.29.4",
    "msw": "0.49.3",
    "omit-empty-es": "1.2.0",
    "prettier": "2.8.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-intl": "^6.4.7",
    "react-redux": "7.2.9",
    "react-router-dom": "5.3.4",
    "redux": "4.2.1",
    "typescript": "5.0.4"
  },
  "resolutions": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@types/eslint": "<9",
    "@types/react": "<18",
    "@types/react-dom": "<18",
    "@types/react-router": "<6",
    "@types/react-router-dom": "<6",
    "headers-polyfill": "3.3.0"
  },
  "devDependencies": {}
}
`

**Comment by ddouglasz** [comment]
Hello @jluterek 
Thank you for reaching out. We are taking a look at it. it seems like a similar issue we had with `msw` and `headers-polyfill` packages. We will update you once we have the fix ready.
Thank you

**Comment by jluterek** [comment]
FYI: When I update headers-polyfill to 3.2.5 I get a different set of results, but it is not 100% passing.

Test Suites: 1 failed, 2 passed, 3 total
Tests:       5 failed, 5 passed, 10 total

**Comment by jluterek** [comment]
Changing the version of headers-polyfill changed the result, but did not give a full pass on yarn test.

Test Suites: 1 failed, 2 passed, 3 total
Tests:       5 failed, 5 passed, 10 total
